# Generated by Django 5.0.1 on 2026-03-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitorDevice',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=16)),
                ('last_seen', models.BigIntegerField(blank=True, help_text='Unix ms', null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='monitoring.bed')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(help_text='Ko‘rsatma matni (xona nomi)', max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('assigned_nurse', models.CharField(blank=True, max_length=255)),
                ('device_battery', models.FloatField(default=100.0)),
                ('admission_date', models.BigIntegerField(help_text='Unix ms')),
                ('hr', models.IntegerField(default=0)),
                ('spo2', models.IntegerField(default=0)),
                ('nibp_sys', models.IntegerField(default=0)),
                ('nibp_dia', models.IntegerField(default=0)),
                ('rr', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=36.6)),
                ('nibp_time', models.BigIntegerField(blank=True, null=True)),
                ('alarm_level', models.CharField(choices=[('none', 'None'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple')], default='none', max_length=16)),
                ('alarm_message', models.TextField(blank=True)),
                ('alarm_patient_id', models.CharField(blank=True, max_length=64)),
                ('alarm_limits', models.JSONField(default=dict)),
                ('news2_score', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('scheduled_interval_ms', models.IntegerField(blank=True, null=True)),
                ('scheduled_next_check', models.BigIntegerField(blank=True, null=True)),
                ('ai_risk', models.JSONField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='monitoring.bed')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('dose', models.CharField(blank=True, max_length=255)),
                ('rate', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='monitoring.patient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('time', models.BigIntegerField()),
                ('is_abnormal', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='monitoring.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('time', models.BigIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='monitoring.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='monitoring.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='monitoring.room'),
        ),
        migrations.CreateModel(
            name='VitalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('hr', models.FloatField()),
                ('spo2', models.FloatField()),
                ('nibp_sys', models.FloatField()),
                ('nibp_dia', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='monitoring.patient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
