# Generated by Django 5.0.1 on 2026-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordevice',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='hl7_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='hl7_port',
            field=models.PositiveIntegerField(default=6006, help_text="Serverda HL7 MLLP tinglash porti (qurilmada ko'rsatilgan port bilan mos)"),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Qurilma ekranidagi lokal IP (tanish uchun)', null=True),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='server_target_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Qurilmada 'Server IP' sifatida kiritilgan manzil (ma'lumot)", null=True),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='subnet_mask',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='monitordevice',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='monitordevice',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='monitordevice',
            name='model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
