# Generated by Django 5.0.1 on 2026-03-22 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_device_hl7_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Monitoring foydalanuvchi profili',
                'verbose_name_plural': 'Monitoring foydalanuvchi profillari',
            },
        ),
        migrations.AlterField(
            model_name='monitordevice',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddField(
            model_name='department',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='monitoring.clinic'),
        ),
        migrations.AddField(
            model_name='monitordevice',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text="Qurilma qaysi klinikaga tegishli (HL7 va ro'yxat filtri).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.clinic'),
        ),
        migrations.AddConstraint(
            model_name='monitordevice',
            constraint=models.UniqueConstraint(fields=('clinic', 'ip_address'), name='monitor_device_clinic_ip_uniq'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_users', to='monitoring.clinic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
