# Generated by Django 5.0.1 on 2026-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_monitordevice_hl7_connect_handshake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordevice',
            name='hl7_connect_handshake',
            field=models.BooleanField(blank=True, help_text="None: HL7_SEND_CONNECT_HANDSHAKE muhiti; True: ulanishda MLLP salom (ba'zi K12); False: yubormaslik.", null=True),
        ),
        migrations.AlterField(
            model_name='monitordevice',
            name='last_hl7_rx_at_ms',
            field=models.BigIntegerField(blank=True, help_text="HL7 paket (MSH+) qabul qilingan vaqt (Unix ms). Faqat haqiqiy HL7 ma'lumot.", null=True),
        ),
    ]
