# Generated by Django 5.2.12 on 2026-04-05 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_patient_clinic_clinicalauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='Klinika nomi')),
                ('clinic_address', models.CharField(blank=True, max_length=512, verbose_name='Manzil')),
                ('clinic_phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('clinic_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Direktor ismi')),
                ('bed_count', models.PositiveIntegerField(default=0, verbose_name='Karavot soni')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Login (username)')),
                ('_password_hash', models.CharField(default='', max_length=256, verbose_name='Parol (hash)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda (tasdiqlanmagan)'), ('active', 'Faol'), ('suspended', "To'xtatilgan"), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=16, verbose_name='Holat')),
                ('active_until', models.DateTimeField(blank=True, help_text="Bo'sh qolsa — cheksiz. Admin o'rnatadi.", null=True, verbose_name='Faollik muddati (gacha)')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Faollashtirilgan vaqt')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Kim faollashtirdi')),
                ('clinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='monitoring.clinic', verbose_name='Klinika (tizimda)')),
                ('clinic_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_registration', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (tizimda)')),
            ],
            options={
                'verbose_name': "Klinika ro'yxati",
                'verbose_name_plural': "Klinika ro'yxatlari",
                'ordering': ['-registered_at'],
            },
        ),
    ]
